### PR TITLE
Adding gain tool

### PR DESCRIPTION
**Pull request by JasonMillward**
Since the mute tool isn't being used currently, I decided to convert it into a 'gain' tool instead.

Works similar to the slip tool, click and drag left / right to lower / raise  the samples gain.

Requires https://github.com/GridSound/webaudio-library/pull/3

### CODE REVIEW

**Comment by Mr21** [comment]
> I decided to convert it into a 'gain' tool instead.
And it's a pretty cool idea!

But I think it will be better if we resize the waveform in a CSS way (`transform: scaleY( gain );`)
Because I like the waveformSVG method simple, this method has to convert the data into a waveform, and the data remain the same with a high or low gain.

I will have to swap the keyboard shortcut about the ma**G**netism.

**Comment by JasonMillward** [comment]
> I will have to swap the keyboard shortcut about the maGnetism.

Ooops. Should have checked the other shortcuts.

> But I think it will be better if we resize the waveform in a CSS way

Agreed, but how would it be done? Something like;

```
elWaveformTmp = that.elSVG.cloneNode( true );
wisdom.css( elWaveformTmp, "transform","scaleY(" + gain + ")" );
```

**Comment by Mr21** [comment]
I will see it later today, thanks again a lot for your interest anyway!
We will have to create a function in the `ui/` code part to update the sample.

Also, you didn't add the equivalent of this [code](https://github.com/GridSound/daw/blob/master/gs/samples/selected/slip.js#L5) in your `samples.selected.gain`, why? Do you think in that specific case it's better without it? The code is not well commented but maybe you understood the min/max code part already.

And after all that, we have to plan on how to save that into the json file.
I will think about it later, thanks again.

Feel free to share any new ideas.

**Comment by JasonMillward** [comment]
> We will have to create a function in the ui/ code part to update the sample.
Makes sense

> Also, you didn't add the equivalent of this code in your samples.selected.gain, why? 

Because in my (limited) testing I found that it works well without it.

**Comment by Mr21** [comment]
This gs.samples.selected.min/max is used to have the min or the max of a certain attribute of every selected samples (in red).

For exemple, when you move many samples up, these functions will avoid that all your samples go in the track n°1. Or you can try to crop severals samples with different duration in the same time.
You will not be able to shrink them all to a duration of 0sec.
I really don't know if it's understandable :/

But in the case of the gain tool, I suppose it will be great, if all the samples receive the same gain value. So it will be okay like that.

**Pull request closed without merging**
